### ISSUE TITLE
Geklaut

### ISSUE THREAD

**Issue by RoyallarsYTVIP** [goulag0/goulag0#1]
Du hast diesen code geklaut hahaha programmier es selbst wenn du es überhaupt kannst

**Comment by goulag0** [comment]
lmfao was für geklaut und was für selber Coden sowas ist nicht mal Coden 😂

**Comment by RoyallarsYTVIP** [comment]
> lmfao was für geklaut und was für selber Coden sowas ist nicht mal Coden 😂

**Comment by RoyallarsYTVIP** [comment]
Hahahahah omg ich habe es auch drin und es ist geklaut so behindert hahaha

**Comment by RoyallarsYTVIP** [comment]
Hast du von Colin dev geklaut

**Comment by goulag0** [comment]
kid fang erstmal kein Beef an und was du machst juckt kein Hund

**Comment by goulag0** [comment]
diggi wie doof bist du man kann es auch selber machen 😂

**Comment by RoyallarsYTVIP** [comment]
Was für kid wie alt bist du 13 hahaha du kennst mein Alter nicht

**Comment by RoyallarsYTVIP** [comment]
Was ich mache juckt keinen hund wie dich es juckt Menschen

**Comment by goulag0** [comment]
Ich bin älter als 14 😂

**Comment by RoyallarsYTVIP** [comment]
HQHQHQHQHQH
